jobs:
- job: 'Ubuntu_1804'
  pool:
    vmImage: 'Ubuntu-18.04'

  steps:
  - template: azure-pipelines-steps.yml

- job: 'Windows_2019'
  pool:
    vmImage: 'windows-2019'

  steps:
  - template: azure-pipelines-steps.yml

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '_build'
      artifactType: 'pipeline'
      artifactName: 'npm-package'

- job: 'MacOS_1015'
  pool:
    vmImage: 'macOS-10.15'

  steps:
  - template: azure-pipelines-steps.yml
