jobs:
- job: 'Ubuntu_1804'
  pool:
    vmImage: 'Ubuntu-18.04'

  steps:
  - template: azure-pipelines-steps.yml

- job: 'Windows_2019'
  pool:
    vmImage: 'windows-2019'

  steps:
  - template: azure-pipelines-steps.yml

  - script: npm pack
    displayName: 'npm pack'
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/releases/2.x'))

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
        '*.tgz'
        'package.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy npm package to staging'
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/releases/2.x'))

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: npm
    displayName: 'Publish npm artifact'
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/releases/2.x'))

- job: 'MacOS_1015'
  pool:
    vmImage: 'macOS-10.15'

  steps:
  - template: azure-pipelines-steps.yml
